### ISSUE TITLE
bug: When compareresults write with high concurrency, there will be lock competition, which will cause the save to fail

### ISSUE THREAD

**Issue by binyu1005** [arextest/arex#125]

**Comment by binyu1005** [comment]
## Call Stack
http post url: http://arex.configuration.uat.qa.nt.ctripcorp.com/api/report/pushCompareResults ,error: I/O error on POST request for "http://arex.configuration.uat.qa.nt.ctripcorp.com/api/report/pushCompareResults": Read timed out; nested exception is java.net.SocketTimeoutException: Read timed out ,request: {"results":[{"planId":"643f643a53ae117f79e16e50","operationId":"63c6657dcd36b002b602977c","serviceName":"flight.settlement.complaintsystem.v1.complaintsystemservice","categoryName":"SOAProvider","diffResultCode":2,"operationName":"flight.settlement.complaintsystem.v1.complaintsystemservice.processInfoSearch","replayId":"","recordId":"AREX-10-42-56-75-23729966841242","recordTime":0,"replayTime":0,"baseMsg":"KLUv/QBQIAEAZXlKdmNtUmxja2xFY3lJNld6SXpOelEzTmpBNU9ESXdYWDA9AQAA","planItemId":"643f643a53ae117f79e16ea2","logs":[{"logInfo":"READY_DEPENDENCY_FAILED","pathPair":{"unmatchedType":0,"leftUnmatchedPath":[],"rightUnmatchedPath":[],"listKeyPath":[]},"warn":0,"logTag":{"errorType":0}}]}]}
org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://arex.configuration.uat.qa.nt.ctripcorp.com/api/report/pushCompareResults": Read timed out; nested exception is java.net.SocketTimeoutException: Read timed out
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:785)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711)
	at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:437)
	at com.arextest.schedule.client.HttpWepServiceApiClient.jsonPost(HttpWepServiceApiClient.java:102)
	at com.arextest.schedule.service.ReplayReportService.write(ReplayReportService.java:141)
	at com.arextest.schedule.service.ReplayReportService.writeIncomparable(ReplayReportService.java:155)
	at com.arextest.schedule.service.ReplayCaseTransmitService.doSendFailedAsFinish(ReplayCaseTransmitService.java:279)
	at com.arextest.schedule.service.ReplayCaseTransmitService.markAllSendStatus(ReplayCaseTransmitService.java:260)
	at com.arextest.schedule.service.ReplayCaseTransmitService.doSendWithDependencyToRemoteHost(ReplayCaseTransmitService.java:118)
	at com.arextest.schedule.service.ReplayCaseTransmitService.send(ReplayCaseTransmitService.java:87)
	at com.arextest.schedule.service.PlanConsumeService.sendByPaging(PlanConsumeService.java:162)
	at com.arextest.schedule.service.PlanConsumeService.sendAllActionCase(PlanConsumeService.java:130)
	at com.arextest.schedule.service.PlanConsumeService.saveActionCaseToSend(PlanConsumeService.java:74)
	at com.arextest.schedule.service.PlanConsumeService.access$100(PlanConsumeService.java:30)
	at com.arextest.schedule.service.PlanConsumeService$ReplayActionLoadingRunnableImpl.doWithTracedRunning(PlanConsumeService.java:60)
	at com.arextest.schedule.mdc.AbstractTracedRunnable.run(AbstractTracedRunnable.java:25)
	at com.dianping.cat.async.CatWrappedRunnable.lambda$run$0(CatWrappedRunnable.java:30)
	at com.dianping.cat.async.CatAsyncSupportTemplate.doExecute4Simple(CatAsyncSupportTemplate.java:147)
	at com.dianping.cat.async.CatAsyncSupportTemplate.execute(CatAsyncSupportTemplate.java:94)
	at com.dianping.cat.async.CatWrappedRunnable.run(CatWrappedRunnable.java:29)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1593)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.springframework.http.client.SimpleClientHttpResponse.getRawStatusCode(SimpleClientHttpResponse.java:55)
	at org.springframework.web.client.DefaultResponseErrorHandler.hasError(DefaultResponseErrorHandler.java:61)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:807)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777)
	... 22 more
