### ISSUE TITLE
bug: Save replay case error

### ISSUE THREAD

**Issue by binyu1005** [arextest/arex#155]
## Description
![固化流程报错了](https://user-images.githubusercontent.com/23733811/235123884-a3f94071-ca98-41fb-8ea4-9b776a769bf9.gif)

## Error message:
 Uncaught error: Cannot read properties of null (reading 'includes')
at HttpBody (http://arex.demo.52koala.com.cn/assets/index-065175b5.js:2338:68) at div at http://arex.demo.52koala.com.cn/assets/index-065175b5.js:630:7560 at P1 (http://arex.demo.52koala.com.cn/assets/index-065175b5.js:432:4921) at http://arex.demo.52koala.com.cn/assets/index-065175b5.js:432:12230 at div at div at TabPanelList (http://arex.demo.52koala.com.cn/assets/index-065175b5.js:630:8008) at div at Tabs$2 (http://arex.demo.52koala.com.cn/assets/index-065175b5.js:630:26159) at Tabs$1 (http://arex.demo.52koala.com.cn/assets/index-065175b5.js:632:8517) at http://arex.demo.52koala.com.cn/assets/index-065175b5.js:16:9599 at div at http://arex.demo.52koala.com.cn/assets/index-065175b5.js:16:9599 at RequestTabs (http://arex.demo.52koala.com.cn/assets/index-065175b5.js:2563:2094) at div at http://arex.demo.52koala.com.cn/assets/index-065175b5.js:16:9599 at div at http://arex.demo.52koala.com.cn/assets/index-065175b5.js:1072:39857 at div at div at http://arex.demo.52koala.com.cn/assets/index-065175b5.js:1072:40041 at http://arex.demo.52koala.com.cn/assets/index-065175b5.js:16:9599 at http://arex.demo.52koala.com.cn/assets/index-065175b5.js:2650:659 at div at http://arex.demo.52koala.com.cn/assets/index-065175b5.js:16:9599 at HttpRequestPage (http://arex.demo.52koala.com.cn/assets/index-065175b5.js:2717:24) at ErrorBoundary (http://arex.demo.52koala.com.cn/assets/index-065175b5.js:3702:757) at div at http://arex.demo.52koala.com.cn/assets/index-065175b5.js:630:7560 at P1 (http://arex.demo.52koala.com.cn/assets/index-065175b5.js:432:4921) at http://arex.demo.52koala.com.cn/assets/index-065175b5.js:432:12230 at div at div at TabPanelList (http://arex.demo.52koala.com.cn/assets/index-065175b5.js:630:8008) at div at Tabs$2 (http://arex.demo.52koala.com.cn/assets/index-065175b5.js:630:26159) at Tabs$1 (http://arex.demo.52koala.com.cn/assets/index-065175b5.js:632:8517) at R1 (http://arex.demo.52koala.com.cn/assets/index-065175b5.js:3687:22008) at DraggableTabs (http://arex.demo.52koala.com.cn/assets/index-065175b5.js:3688:15616) at http://arex.demo.52koala.com.cn/assets/index-065175b5.js:3891:1975 at http://arex.demo.52koala.com.cn/assets/index-065175b5.js:16:9599 at div at div at Spin$1 (http://arex.demo.52koala.com.cn/assets/index-065175b5.js:707:13554) at SpinFC$1 (http://arex.demo.52koala.com.cn/assets/index-065175b5.js:707:14926) at div at http://arex.demo.52koala.com.cn/assets/index-065175b5.js:16:9599 at FullHeightSpin (http://arex.demo.52koala.com.cn/assets/index-065175b5.js:948:39) at EmptyWrapper (http://arex.demo.52koala.com.cn/assets/index-065175b5.js:939:33) at MainTabs (http://arex.demo.52koala.com.cn/assets/index-065175b5.js:3891:26) at div at http://arex.demo.52koala.com.cn/assets/index-065175b5.js:1072:39857 at div at div at http://arex.demo.52koala.com.cn/assets/index-065175b5.js:1072:40041 at http://arex.demo.52koala.com.cn/assets/index-065175b5.js:16:9599 at MainBox (http://arex.demo.52koala.com.cn/assets/index-065175b5.js:3961:16) at RenderedRoute (http://arex.demo.52koala.com.cn/assets/index-065175b5.js:258:5058) at main at http://arex.demo.52koala.com.cn/assets/index-065175b5.js:520:8514 at section at http://arex.demo.52koala.com.cn/assets/index-065175b5.js:520:8936 at div at App$3 (http://arex.demo.52koala.com.cn/assets/index-065175b5.js:485:22895) at div at http://arex.demo.52koala.com.cn/assets/index-065175b5.js:16:9599 at ThemeProvider (http://arex.demo.52koala.com.cn/assets/index-065175b5.js:16:10022) at EmotionThemeProvider (http://arex.demo.52koala.com.cn/assets/index-065175b5.js:2005:12706) at FormProvider$2 (http://arex.demo.52koala.com.cn/assets/index-065175b5.js:338:46742) at LocaleProvider (http://arex.demo.52koala.com.cn/assets/index-065175b5.js:338:56237) at ProviderChildren (http://arex.demo.52koala.com.cn/assets/index-065175b5.js:378:2825) at ConfigProvider (http://arex.demo.52koala.com.cn/assets/index-065175b5.js:378:5149) at GlobalConfigProvider (http://arex.demo.52koala.com.cn/assets/index-065175b5.js:2005:12874) at App (http://arex.demo.52koala.com.cn/assets/index-065175b5.js:3991:176) at Router (http://arex.demo.52koala.com.cn/assets/index-065175b5.js:258:7589) at BrowserRouter (http://arex.demo.52koala.com.cn/assets/index-065175b5.js:267:487)

**Comment by coryhh** [comment]
https://github.com/arextest/arex-report/pull/174/files

**Comment by coryhh** [comment]
https://github.com/arextest/arex-report/pull/174
