### ISSUE TITLE
Unknown frame descriptor

### ISSUE THREAD

**Issue by waroyhz** [arextest/arex#171]
按照demo在k8s部署arex
spring boot version:2.3.7.RELEASE、2.7.11
docker运行镜像: amd64/eclipse-temurin:17-jdk-centos7、amd64/eclipse-temurin:8-jdk-centos7 

`-javaagent:/arex-agent/arex-agent-0.2.0.jar -Darex.config.path=/arex-agent/arex.agent.conf`

arex.agent.conf:
`
arex.service.name=jira-manage
arex.storage.service.host=arex-beta-release-arex-report.arex-beta:8080`

运行报错如下：
`[http-nio-8090-exec-4] INFO io.arex.inst.runtime.context.ContextManager - clean up expired count: 1, arex-record-id: AREX-10-42-21-205-3672621530
2023-05-13 23:03:20.774  INFO 11 --- [nio-8090-exec-4] com.cj.tapd.service.TapdDataService      : 使用缓存 getInterationState
[I/O dispatcher 1] WARN io.arex.foundation.util.CompressUtil - [[title=arex.decompress]]
2023-05-13T15:03:21.298659023Z com.github.luben.zstd.ZstdIOException: Unknown frame descriptor
2023-05-13T15:03:21.298663250Z 	at com.github.luben.zstd.ZstdInputStreamNoFinalizer.readInternal(ZstdInputStreamNoFinalizer.java:179)
2023-05-13T15:03:21.298666874Z 	at com.github.luben.zstd.ZstdInputStreamNoFinalizer.read(ZstdInputStreamNoFinalizer.java:131)
2023-05-13T15:03:21.298669860Z 	at com.github.luben.zstd.ZstdInputStream.read(ZstdInputStream.java:92)
2023-05-13T15:03:21.298672768Z 	at io.arex.foundation.util.CompressUtil.zstdDecompress(CompressUtil.java:64)
2023-05-13T15:03:21.298675567Z 	at io.arex.foundation.util.AsyncHttpClientUtil.lambda$executeAsync$1(AsyncHttpClientUtil.java:106)
2023-05-13T15:03:21.298678553Z 	at io.arex.foundation.util.AsyncHttpClientUtil$ResponseCallback.completed(AsyncHttpClientUtil.java:191)
2023-05-13T15:03:21.298682165Z 	at io.arex.foundation.util.AsyncHttpClientUtil$ResponseCallback.completed(AsyncHttpClientUtil.java:170)
2023-05-13T15:03:21.298685243Z 	at shaded.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:123)
	at shaded.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:181)
2023-05-13T15:03:21.298704268Z 	at shaded.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:442)
2023-05-13T15:03:21.298707254Z 	at shaded.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:332)
2023-05-13T15:03:21.298710124Z 	at shaded.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
2023-05-13T15:03:21.298713118Z 	at shaded.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
2023-05-13T15:03:21.298715981Z 	at shaded.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
2023-05-13T15:03:21.298718880Z 	at shaded.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
2023-05-13T15:03:21.298751468Z 	at shaded.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
2023-05-13T15:03:21.298754800Z 	at shaded.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
2023-05-13T15:03:21.298757536Z 	at shaded.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
2023-05-13T15:03:21.298760285Z 	at shaded.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
2023-05-13T15:03:21.298763751Z 	at shaded.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
2023-05-13T15:03:21.298766395Z 	at shaded.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
2023-05-13T15:03:21.298769193Z 	at java.base/java.lang.Thread.run(Thread.java:833)
2023-05-13T15:03:21.298772020Z [I/O dispatcher 1] WARN io.arex.foundation.util.AsyncHttpClientUtil - [[title=arex.completed]]response bytes: eyJyZXNwb25zZVN0YXR1c1R5cGUiOnsicmVzcG9uc2VDb2RlIjo0LCJyZXNwb25zZURlc2MiOi
JBdXRoZW50aWNhdGlvbiB2ZXJpZmljYXRpb24gZmFpbGVkIiwidGltZXN0YW1wIjoxNjgzOTkwMjAyNTExfSwiYm9keSI6bnVsbH0=
[I/O dispatcher 2] WARN io.arex.foundation.util.CompressUtil - [[title=arex.decompress]]
2023-05-13T15:03:21.300574224Z com.github.luben.zstd.ZstdIOException: Unknown frame descriptor
2023-05-13T15:03:21.300577520Z 	at com.github.luben.zstd.ZstdInputStreamNoFinalizer.readInternal(ZstdInputStreamNoFinalizer.java:179)
2023-05-13T15:03:21.300580678Z 	at com.github.luben.zstd.ZstdInputStreamNoFinalizer.read(ZstdInputStreamNoFinalizer.java:131)
2023-05-13T15:03:21.300591415Z 	at com.github.luben.zstd.ZstdInputStream.read(ZstdInputStream.java:92)
2023-05-13T15:03:21.300594432Z 	at io.arex.foundation.util.CompressUtil.zstdDecompress(CompressUtil.java:64)
2023-05-13T15:03:21.300597113Z 	at io.arex.foundation.util.AsyncHttpClientUtil.lambda$executeAsync$1(AsyncHttpClientUtil.java:106)
2023-05-13T15:03:21.300601886Z 	at io.arex.foundation.util.AsyncHttpClientUtil$ResponseCallback.completed(AsyncHttpClientUtil.java:191)
2023-05-13T15:03:21.300609071Z 	at io.arex.foundation.util.AsyncHttpClientUtil$ResponseCallback.completed(AsyncHttpClientUtil.java:170)
2023-05-13T15:03:21.300612036Z 	at shaded.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:123)
2023-05-13T15:03:21.300614708Z 	at shaded.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:181)
2023-05-13T15:03:21.300617542Z 	at shaded.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:442)
2023-05-13T15:03:21.300620249Z 	at shaded.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:332)
2023-05-13T15:03:21.300622923Z 	at shaded.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
2023-05-13T15:03:21.300625587Z 	at shaded.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
2023-05-13T15:03:21.300628471Z 	at shaded.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at shaded.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
2023-05-13T15:03:21.300643093Z 	at shaded.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
2023-05-13T15:03:21.300645902Z 	at shaded.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
2023-05-13T15:03:21.300648632Z 	at shaded.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
2023-05-13T15:03:21.300651290Z 	at shaded.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
2023-05-13T15:03:21.300653932Z 	at shaded.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
2023-05-13T15:03:21.300656488Z 	at shaded.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
2023-05-13T15:03:21.300659271Z 	at java.base/java.lang.Thread.run(Thread.java:833)
2023-05-13T15:03:21.300785516Z [I/O dispatcher 2] WARN io.arex.foundation.util.AsyncHttpClientUtil - [[title=arex.completed]]response bytes: eyJyZXNwb25zZVN0YXR1c1R5cGUiOnsicmVzcG9uc2VDb2RlIjo0LCJyZXNwb25zZURlc2MiOiJBdXRoZW50aWNhdGlvbiB2ZXJpZmljYXRpb24gZmFpbGVkIiwidGltZXN0YW1wIjoxNjgzOTkwMjAyNTExfSwiYm9keSI6bnVsbH0=
[arex-timer-service-1-thread-1] INFO io.arex.foundation.services.ConfigService - [arex] load agent config
2023-05-13T15:03:44.602972534Z request: {"appId":"jira-manage","recordVersion":"0.2.0","host":"10.42.21.205"}
2023-05-13T15:03:44.602977333Z response: {"responseStatusType":{"responseCode":0,"responseDesc":"success","timestamp":1683990225819},"body":{"serviceCollectConfiguration":{"status":null,"modifiedTime":1683988242790,"appId":"jira-manage","sampleRate":100,"allowDayOfWeeks":127,"timeMock":false,"allowTimeOfDayFrom":"00:01","allowTimeOfDayTo":"23:59","excludeServiceOperationSet":null},"dynamicClassConfigurationList":null,"status":3}}
2023-05-13T15:03:44.602990517Z `

**Comment by lucas-myx** [comment]
`WARN io.arex.foundation.util.AsyncHttpClientUtil - [[title=arex.completed]]response bytes: eyJyZXNwb25zZVN0YXR1c1R5cGUiOnsicmVzcG9uc2VDb2RlIjo0LCJyZXNwb25zZURlc2MiOi JBdXRoZW50aWNhdGlvbiB2ZXJpZmljYXRpb24gZmFpbGVkIiwidGltZXN0YW1wIjoxNjgzOTkwMjAyNTExfSwiYm9keSI6bnVsbH0=`

默认arex-agent和arex-storage之间数据交互的格式是zstd，但这个不是，试着用base64解压后数据如下：
```
{
 "responseStatusType": {
 "responseCode": 4,
 "responseDesc": "Authentication verification failed",
 "timestamp": 1683990202511
 },
 "body": null
}
```
应该是没有调到arex-storage服务，被网关拦截了（好像是鉴权之类的服务），可以确认下

**Comment by waroyhz** [comment]
把agent启动配置调整为如下，已经正常解决，感谢。

-javaagent:/arex-agent/arex-agent-0.2.0.jar -Darex.enable.debug=true -Darex.service.name=jira-manage -Darex.storage.service.host=arex-beta-release-arex-storage.arex-beta:8080

**Comment by waroyhz** [comment]
把agent启动配置调整为如下，已经正常解决，感谢。

-javaagent:/arex-agent/arex-agent-0.2.0.jar -Darex.enable.debug=true -Darex.service.name=jira-manage -Darex.storage.service.host=arex-beta-release-arex-storage.arex-beta:8080
